export const TEAM_COOKIE = "oh_team_session";
export const ADMIN_COOKIE = "oh_admin_session";

export const TEAM_STATUS = {
  REGISTERED: "REGISTERED",
  WAITING: "WAITING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  QUALIFIED: "QUALIFIED",
  DISQUALIFIED: "DISQUALIFIED",
  TERMINATED: "TERMINATED",
} as const;

export type TeamStatus = (typeof TEAM_STATUS)[keyof typeof TEAM_STATUS];

export const BLOCKED_STATUSES = [TEAM_STATUS.DISQUALIFIED, TEAM_STATUS.TERMINATED];

export const SESSION_STATUS = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  TERMINATED: "TERMINATED",
  EXPIRED: "EXPIRED",
} as const;

export const MALPRACTICE_EVENT_TYPES = [
  "RIGHT_CLICK",
  "COPY_ATTEMPT",
  "CUT_ATTEMPT",
  "PASTE_ATTEMPT",
  "TAB_SWITCH",
  "WINDOW_BLUR",
  "FULLSCREEN_EXIT",
  "DEVTOOLS_SIGNAL",
  "SCREEN_CAPTURE_SIGNAL",
  "NAVIGATION_ATTEMPT",
  "MULTIPLE_SESSION_ATTEMPT",
  "OTHER",
] as const;

export type MalpracticeEventType = (typeof MALPRACTICE_EVENT_TYPES)[number];

export const MAX_MALPRACTICE_STRIKES = 3;

export const EVENT_SEVERITY: Record<MalpracticeEventType, "LOW" | "MEDIUM" | "HIGH"> = {
  RIGHT_CLICK: "LOW",
  COPY_ATTEMPT: "MEDIUM",
  CUT_ATTEMPT: "MEDIUM",
  PASTE_ATTEMPT: "MEDIUM",
  TAB_SWITCH: "HIGH",
  WINDOW_BLUR: "MEDIUM",
  FULLSCREEN_EXIT: "HIGH",
  DEVTOOLS_SIGNAL: "HIGH",
  SCREEN_CAPTURE_SIGNAL: "MEDIUM",
  NAVIGATION_ATTEMPT: "MEDIUM",
  MULTIPLE_SESSION_ATTEMPT: "MEDIUM",
  OTHER: "LOW",
};
